@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-type: application/json

{
    "name": "testew222",
    "email": "tet222dae@example.com",
    "password": "123456"
}


###
# @name authenticate
POST {{baseUrl}}/sessions
Content-type: application/json

{
    "email": "gabi@example.com",
    "password": "123456"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "dkadioawjiodawjiodawdadwadawdaw",
    "content": "Conteudo da pergunta"
}


###
# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-type: application/json
Authorization: Bearer {{authToken}}
